const DeviceObj = {
  windows: "https://imgur.com/AP0dcEa.jpg",
  mac: "https://imgur.com/GfknMdO.jpg",
  linux: "https://imgur.com/hbFGLql.jpg",
};
const SHOP_DATA = [
  {
    title: "Action",
    items: [
      {
        id: 1,
        name: "Hades",
        imageUrl: "https://imgur.com/pTDctK7.jpg",
        price: 1299,
        description:
          "Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre. Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre.",
        developer: "Supergiant Games",
        ratings: "4 / 5",
        players: "2M",
        mrp: 2500,
        year: 2020,
        gameSize: "20 GB",
        ss: ["https://imgur.com/sVWqsyd.jpg", "https://imgur.com/uSdeRhQ.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 2,
        name: "Hollow Knight",
        imageUrl: "https://imgur.com/WA2WMEF.jpg",
        price: 999,
        description:
          "Beneath the fading town of Dirtmouth sleeps an ancient, ruined kingdom. Many are drawn below the surface, searching for riches, or glory, or answers to old secrets Hollow Knight is a classically styled 2D action adventure across a vast interconnected world. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs; and solve ancient mysteries at the kingdoms heart",
        developer: "Team Cherry",
        ratings: "4.5 / 5",
        players: "1.5M",
        mrp: 1999,
        year: 2017,
        gameSize: "9 GB",
        ss: ["https://imgur.com/63bV9gB.jpg", "https://imgur.com/c0MabB7.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 3,
        name: "Furi",
        imageUrl: "https://imgur.com/mMs0nPY.jpg",
        price: 1100,
        description:
          "The jailer is the key, kill him and you'll be free. Fight your way free in this ultra-responsive, fast-paced sword-fighting and dual-stick shooting game.",
        developer: "The Game Bakers",
        ratings: "4 / 5",
        players: "99k",
        mrp: 1599,
        year: 2016,
        gameSize: "5 GB",
        ss: ["https://imgur.com/QYQhK3V.jpg", "https://imgur.com/xSJPJXd.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 4,
        name: "SteamWorld Dig 2",
        imageUrl: "https://imgur.com/1HNkqPB.jpg",
        price: 1899,
        description:
          "Adventure Waits Below the Surface...SteamWorld Dig 2 takes you on a platform mining adventure forged in Metroidvania flames. When an old trading town is struck by mysterious earthquakes, it's up to a lone steambot and her unlikely companion to uncover what trembling terrors lie beneath.Dig your way underground and explore vivid worlds riddled with treasure, secrets and traps.Combat dangerous enemies at every turn of the underworld's twisted paths, including shadowy creatures and the haunted remains of an ancient electrical threat.And finally, learn the truth about your long lost friend…",
        developer: "Image & Form Games",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3499,
        year: 2017,
        gameSize: "400 MB",
        ss: ["https://imgur.com/RPb96p7.jpg", "https://imgur.com/Jjb5GlT.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 5,
        name: "Dead Cells",
        imageUrl: "https://imgur.com/MBy3d3I.jpg",
        price: 1399,
        description:
          "Dead Cells is a roguelike, Castlevania-inspired action-platformer, allowing you to explore a sprawling, ever-changing castle… assuming you’re able to fight your way past its keepers. To beat the game you’ll have to master 2D souls-like like combat with the ever present threat of permadeath looming. No checkpoints. Kill, die, learn, repeat.",
        developer: "Motion Twin Scop ARL",
        ratings: "4.9 / 5",
        players: "3M",
        mrp: 2599,
        year: 2018,
        gameSize: "500 MB",
        ss: ["https://imgur.com/Ue9ggpi.jpg", "https://imgur.com/V5f0eD0.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 6,
        name: "Hotline Miami",
        imageUrl: "https://imgur.com/kC0TIAW.jpg",
        price: 1000,
        description:
          "Hotline Miami is a high-octane action game overflowing with raw brutality, hard-boiled gunplay and skull crushing close combat. Set in an alternative 1989 Miami, you will assume the role of a mysterious man on a murderous rampage against the shady underworld at the behest of voices on your answering DeviceObj.machine. Rely on your wits to choreograph your way through seemingly impossible situations as you constantly find yourself outnumbered by vicious enemies. The action is unrelenting and every shot is instantly fatal, each move must be quick if you hope to survive long enough to unveil the sinister forces driving the bloodshed. ",
        developer: "Devolver Digital",
        ratings: "5 / 5",
        players: "10M",
        mrp: 3599,
        year: 2012,
        gameSize: "500 MB",
        ss: ["https://imgur.com/YbhDZDd.jpg", "https://imgur.com/affLztL.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 7,
        name: "Cuphead",
        imageUrl: "https://imgur.com/AK8IkFd.jpg",
        price: 999,
        description:
          "Cuphead features one or two players taking control of animated characters Cuphead and his brother Mugman to fight through several levels that culminate in boss fights as to repay their debt to The Devil. The game was praised for its art style and noted for its challenging difficulty. It was both a critical and commercial success, winning several awards and selling over four million copies by July 2019. An animated series based on the game, entitled The Cuphead Show!, is on Netflix.",
        developer: "Studio MDHR",
        ratings: "4.6 / 5",
        players: "1M",
        mrp: 2599,
        year: 2017,
        gameSize: "4 GB",
        ss: ["https://imgur.com/xKgS0qD.jpg", "https://imgur.com/N4wI6Wy.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 8,
        name: "Rocket League",
        imageUrl: "https://imgur.com/Fxn6RqA.jpg",
        price: 499,
        description:
          "Hit the field by yourself or with friends in 1v1, 2v2, and 3v3 Online Modes, or enjoy Extra Modes like Rumble, Snow Day, or Hoops. Unlock items in Rocket Pass, climb the Competitive Ranks, compete in Competitive Tournaments, complete Challenges, enjoy cross-platform progression and more! The field is waiting. Take your shot!",
        developer: "Psyonix",
        ratings: "4 / 5",
        players: "15M",
        mrp: 3099,
        year: 2015,
        gameSize: "10 GB",
        ss: ["https://imgur.com/hBNZYo4.jpg", "https://imgur.com/akKhJGj.jpg"],
        devices: [DeviceObj.windows, DeviceObj.mac],
      },
      {
        id: 9,
        name: "Sifu",
        imageUrl: "https://imgur.com/FVxd1Op.jpg",
        price: 1199,
        description:
          "Whether you choose to play as a male or a female character, in Sifu, you will ponder that question on your path for revenge, hunting down your family’s assassins. One against all, you have no allies, countless enemies, and a mysterious amulet to bring you back to life every time you die. Yet, be warned! Your secret weapon comes with a hefty price to pay: aging and its consequences.",
        developer: "Sloclap",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2023,
        gameSize: "22 GB",
        ss: ["https://imgur.com/HevGuuq.jpg", "https://imgur.com/LtiMvaw.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 10,
        name: "Fall Guys: Ultimate Knockout",
        imageUrl: "https://imgur.com/BFFRp3n.jpg",
        price: 699,
        description:
          "Fall Guys is a free-to-play platform battle royale game developed by Mediatonic and published by Epic Games. The game involves up to 40 players who control jellybean-like characters and compete against each other in a series of randomly selected mini-games such as obstacle courses or soccer. ",
        developer: "Mediatonic",
        ratings: "3.5 / 5",
        players: "5M",
        mrp: 1599,
        year: 2020,
        gameSize: "2 GB",
        ss: ["https://imgur.com/xsuV3Lg.jpg", "https://imgur.com/xMylu2e.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 11,
        name: "Deep Rock Galactic",
        imageUrl: "https://imgur.com/USn8R5C.jpg",
        price: 1299,
        description:
          "Work together as a team to dig, explore, and fight your way through a massive cave system filled with hordes of deadly enemies and valuable resources. You will need to rely on your teammates if you want to survive the most hostile cave systems in the galaxy!. Explore a network of procedurally generated cave systems filled with enemies to fight and riches to collect. There's always something new to discover and no two playthroughs are alike. ",
        developer: "Ghost Ship Games",
        ratings: "4.8 / 5",
        players: "990k",
        mrp: 2599,
        year: 2018,
        gameSize: "3 GB",
        ss: ["https://imgur.com/mbigOlp.jpg", "https://imgur.com/o60Rq79.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 12,
        name: "Blasphemous",
        imageUrl: "https://imgur.com/BZEnm6I.jpg",
        price: 499,
        description:
          "Blasphemous is a Metroidvania video game developed by Spanish studio The Game Kitchen and published by Team17. The game was released for Microsoft DeviceObj.windows, PlayStation 4, Xbox One, and Nintendo Switch on 10 September 2019, with Warp Digital handling the console ports.",
        developer: " The Game Kitchen S.L",
        ratings: "4.6 / 5",
        players: "950k",
        mrp: 2199,
        year: 2019,
        gameSize: "4 GB",
        ss: ["https://imgur.com/Vb36MUp.jpg", "https://imgur.com/6imNZjN.jpg"],
        devices: [DeviceObj.windows, DeviceObj.mac],
      },
      {
        id: 13,
        name: "Superhot VR",
        imageUrl: "https://imgur.com/HgfLvVh.jpg",
        price: 2199,
        description:
          "Lose track of what's real. Commit yourself, body and mind. Confront the evocative, elegantly brutal world of SUPERHOT VR. Enemies pouring into the room from all sides, dozens of bullets coursing through the air... Wait. Something seems different in here...",
        developer: "SUPERHOT Team",
        ratings: "4.5 / 5",
        players: "1M",
        mrp: 3599,
        year: 2017,
        gameSize: "4 GB",
        ss: ["https://imgur.com/nCaXEEB.jpg", "https://imgur.com/b9XBzNv.jpg"],
        devices: [DeviceObj.windows],
      },
    ],
  },
  {
    title: "Adventure",
    items: [
      {
        id: 14,
        name: "Return of the Obra Dinn",
        imageUrl: "https://imgur.com/akMpAPk.jpg",
        price: 1650,
        description:
          "In 1802, the merchant ship Obra Dinn set out from London for the Orient with over 200 tons of trade goods. Six months later it hadn't met its rendezvous point at the Cape of Good Hope and was declared lost at sea.Early this morning of October 14th, 1807, the Obra Dinn drifted into port at Falmouth with damaged sails and no visible crew. As insurance investigator for the East India Company's London Office, dispatch immediately to Falmouth, find means to board the ship, and prepare an assessment of damages.Return of the Obra Dinn is a first-person mystery adventure based on exploration and logical deduction.",
        developer: "Lucas Pope",
        ratings: "4.7 / 5",
        players: "200k",
        mrp: 3299,
        year: 2018,
        gameSize: "2 GB",
        ss: ["https://imgur.com/6HL8Imk.jpg", "https://imgur.com/dsjU0SZ.jpg"],
        devices: [DeviceObj.windows, DeviceObj.mac],
      },
      {
        id: 15,
        name: "Outer Wilds",
        imageUrl: "https://imgur.com/gM70RcY.jpg",
        price: 1399,
        description:
          "You're the newest member of Outer Wilds Ventures, a fledgling space program searching for answers in a strange, constantly changing solar system. To solve these mysteries you'll have to venture into the most dangerous reaches of space.",
        developer: "Mobius Entertainment",
        ratings: "4.7 / 5",
        players: "2M",
        mrp: 3599,
        year: 2019,
        gameSize: "8 GB",
        ss: ["https://imgur.com/RtjfH92.jpg", "https://imgur.com/OmfcV1w.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 16,
        name: "Citizen Sleeper",
        imageUrl: "https://imgur.com/2DN0wzm.jpg",
        price: 1100,
        description:
          "Roleplaying in the ruins of interplanetary capitalism. Live the life of an escaped worker, washed-up on a lawless station at the edge of an interstellar society. Inspired by the flexibility and freedom of TTRPGs, explore the station, choose your friends, escape your past and change your future.",
        developer: "Jump Over The Age",
        ratings: "4.5 / 5",
        players: "765k",
        mrp: 2599,
        year: 2022,
        gameSize: "2 GB",
        ss: ["https://imgur.com/sv9fGKI.jpg", "https://imgur.com/IDuMsJU.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 17,
        name: "Terraria",
        imageUrl: "https://imgur.com/afLYUT4.jpg",
        price: 1600,
        description:
          "Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, DeviceObj.machinery, and aesthetics? Perhaps you will choose instead to seek out ever-greater foes to test your mettle in combat? Maybe you will decide to construct your own city to house the host of mysterious allies you may encounter along your travels?",
        developer: " Re-Logic, Engine Software, Pipeworks Studio, Codeglue,",
        ratings: "4.8 / 5",
        players: "5M",
        mrp: 3599,
        year: 2011,
        gameSize: "300 MB",
        ss: ["https://imgur.com/psJI6wW.jpg", "https://imgur.com/sPOvjL2.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 18,
        name: "To the Moon",
        imageUrl: "https://imgur.com/3ApfVEN.jpg",
        price: 1499,
        description:
          "This particular story follows their attempt to fulfill the dream of an elderly man, Johnny. With each step back in time, a new fragment of Johnny's past is revealed. As the two doctors piece together the puzzled events that spanned a life time, they seek to find out just why the frail old man chose his dying wish to be what it is. And Johnny's last wish is, of course... to go to the moon.",
        developer: "Freebird Games",
        ratings: "4.9 / 5",
        players: "599k",
        mrp: 2499,
        year: 2011,
        gameSize: "100 MB",
        ss: ["https://imgur.com/GI9j2lo.jpg", "https://imgur.com/H7bqzSU.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 19,
        name: "Crypt of the Necrodancer",
        imageUrl: "https://imgur.com/XG7xkSt.jpg",
        price: 799,
        description:
          "Crypt of the NecroDancer is a roguelike rhythm video game developed and published by Canadian independent game studio Brace Yourself Games. The game takes fundamental elements of a roguelike dungeon exploration game and adds a beat-matching rhythm game set to an original soundtrack written by Danny Baranowsky.",
        developer: "Brace Yourself Games, Blitworks",
        ratings: "4.6 / 5",
        players: "990k",
        mrp: 1599,
        year: 2017,
        gameSize: "1.6 GB",
        ss: ["https://imgur.com/m84gcO2.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 20,
        name: "What Remains of Edith Finch",
        imageUrl: "https://imgur.com/lSIJujl.jpg",
        price: 2599,
        description:
          "What Remains of Edith Finch is a collection of strange tales about a family in Washington state. As Edith, you'll explore the colossal Finch house, searching for stories as she explores her family history and tries to figure out why she's the last one in her family left alive.",
        developer: "Giant Sparrow",
        ratings: "4.8 / 5",
        players: "1M",
        mrp: 3599,
        year: 2017,
        gameSize: "5 GB",
        ss: ["https://imgur.com/Au8JJQA.jpg", "https://imgur.com/dkFtNVy.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 21,
        name: "The Stanley Parable: Ultra Deluxe",
        imageUrl: "https://imgur.com/uQj7kIK.jpg",
        price: 2000,
        description:
          "The Stanley Parable is an interactive storytelling and walking simulator video game designed by American developer Davey Wreden. The game was originally released on July 27, 2011 as a free modification for Half-Life 2. A high-definition stand-alone remake, including new story elements, was again designed by Davey Wreden together with Source engine modeler William Pugh, under the Galactic Cafe studio name. The remake was announced and approved via Steam Greenlight in 2012, and was released on October 17, 2013 for Microsoft DeviceObj.windows. Later updates of the game added support for OS X on December 19, 2013, and for DeviceObj.linux on September 9, 2015. A PlayStation 4 version was released on November 13, 2018, and an Xbox One version was released on December 4, 2018. A Nintendo Switch version was released on March 26, 2020. The game was praised for its humor and narrative.",
        developer: "Galactic Cafe",
        ratings: "4.7 / 5",
        players: "2M",
        mrp: 3599,
        year: 2013,
        gameSize: "5 GB",
        ss: ["https://imgur.com/PhnvtT2.jpg", "https://imgur.com/KOq0NOt.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 22,
        name: "Doki Doki Literature Club Plus",
        imageUrl: "https://imgur.com/3xYnqQ0.jpg",
        price: 1599,
        description:
          "Welcome to a terrifying world of poetry and romance! Write poems for your crush and erase any mistakes along the way to ensure your perfect ending. Now’s your chance to discover why DDLC is one of the most beloved psychological horror games of the decade! You play as the main character, who reluctantly joins the Literature Club in search of a romantic interest. With every poem you write and every choice you make, you’ll charm your crush and begin to unfold the horrors of school romance. Do you have what it takes to crack the code of dating sims and get the perfect ending? Now, the original mind-shattering DDLC experience is packed with tons of new features and content exclusive to Doki Doki Literature Club Plus!",
        developer: "Team Salvato",
        ratings: "4.7 / 5",
        players: "1M",
        mrp: 3599,
        year: 2021,
        gameSize: "5 GB",
        ss: ["https://imgur.com/AgQatuB.jpg", "https://imgur.com/1ei6VUY.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 23,
        name: "As Dusk Falls",
        imageUrl: "https://imgur.com/ZdNFnf9.jpg",
        price: 599,
        description:
          "As Dusk Falls is an original interactive drama from INTERIOR/NIGHT that explores the entangled lives of two families across thirty years. Starting in 1998 with a robbery-gone-wrong in small town Arizona, the choices you make have a powerful impact on the characters’ lives in this uncompromising story of betrayal, sacrifice and resilience.",
        developer: "INTERIOR/NIGHT",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 1599,
        year: 2022,
        gameSize: "8 GB",
        ss: ["https://imgur.com/KWXtTwk.jpg", "https://imgur.com/TzXsLSb.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 24,
        name: "Night in the Woods",
        imageUrl: "https://imgur.com/M1n3Wku.jpg",
        price: 1799,
        description:
          "Night in the Woods is a single-player adventure game. It is presented in a 2D perspective, in which players control a cat-like character named Mae, who recently dropped out of college and has returned to her hometown to find unexpected change. The game follows a linear plot, with numerous cutscenes and story segments between playable sections. Mae explores the town to interact with its citizens, engage with the environment, and progress through the main story. The game also features platforming elements, with players using Mae's ability to jump and cling to walls to explore the environment, and to access areas that are not reachable otherwise. The game also features a day-night cycle, during which certain areas are accessible or events are triggered. The game also features a number of minigames, including a rhythm game and a text-based adventure game.",
        developer: "Infinite Fall",
        ratings: "4.9 / 5",
        players: "1M",
        mrp: 3599,
        year: 2017,
        gameSize: "5 GB",
        ss: ["https://imgur.com/2i7msdV.jpg", "https://imgur.com/9JPZuyP.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 25,
        name: "Brothers: A Tale of Two Sons",
        imageUrl: "https://imgur.com/XzAiF1g.jpg",
        price: 2899,
        description:
          "Brothers: A Tale of Two Sons is an adventure game developed by Starbreeze Studios and published by 505 Games for Xbox 360, Microsoft DeviceObj.windows, PlayStation 3, PlayStation 4, Xbox One, iOS, Android, DeviceObj.windows Phone, and Nintendo Switch. The game takes place in a fantasy world filled with fictitious creatures like orcs and trolls. The story talks about two young brothers who set out on a journey to find a cure for their father, who has fallen ill. The brothers are accompanied by a bird-like creature, which players can use to interact with the game's environment and to solve puzzles. The game is presented from a third-person perspective which players can use to control both brothers at the same time, though in some instances, the player may control only one brother while the AI controls the other.",
        developer: "Starbreeze Studios",
        ratings: "4.5 / 5",
        players: "5M",
        mrp: 3599,
        year: 2013,
        gameSize: "3 GB",
        ss: [],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 26,
        name: "Jazzpunk",
        imageUrl: "https://imgur.com/3xunEkp.jpg",
        price: 1599,
        description:
          "Jazzpunk is a single-player adventure game. It is presented in a 2D perspective, in which players control a cat-like character named Mae, who recently dropped out of college and has returned to her hometown to find unexpected change. The game follows a linear plot, with numerous cutscenes and story segments between playable sections. Mae explores the town to interact with its citizens, engage with the environment, and progress through the main story. The game also features platforming elements, with players using Mae's ability to jump and cling to walls to explore the environment, and to access areas that are not reachable otherwise. The game also features a day-night cycle, during which certain areas are accessible or events are triggered. The game also features a number of minigames, including a rhythm game and a text-based adventure game.",
        developer: "Necrophone Games",
        ratings: "4.9 / 5",
        players: "990k",
        mrp: 2599,
        year: 2014,
        gameSize: "5 GB",
        ss: ["https://imgur.com/BZ2If2S.jpg", "https://imgur.com/yT9erRV.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 27,
        name: "Abzu",
        imageUrl: "https://imgur.com/TpbcjmK.jpg",
        price: 1899,
        description:
          "Abzû is an adventure game played from a third-person perspective. Players assume control of a diver who can swim freely around the ocean. The diver can interact with the environment in a variety of ways; aside from swimming, the diver can also use a boost mechanic to speed up, and charge at objects and other aquatic life. Using these abilities, the diver can interact with marine life and some flora and fauna, such as riding a dolphin and sea turtles, or hitching a ride on great white sharks by grabbing on their fins. As the game progresses, the diver unlocks new areas and pursues the secrets behind the forces harming the local environment. The ocean is filled with many secrets and collectables hidden throughout the environment, such as different species of fish, hidden cave systems, and sunken ruins.",
        developer: "Giant Squid Studios",
        ratings: "4.5 / 5",
        players: "999k",
        mrp: 3599,
        year: 2016,
        gameSize: "6 GB",
        ss: ["https://imgur.com/A6yhr7m.jpg", "https://imgur.com/0T1g3f3.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 28,
        name: "Journey",
        imageUrl: "https://imgur.com/F3ZljVZ.jpg",
        price: 2499,
        description:
          "Journey is an adventure game played from a third-person perspective. Players assume control of a robed figure that can jump, glide, and fly across a vast desert, with the goal to reach the mountaintop far in the distance. The game features no map or instructions, only a goal guided by the light from the mountaintop. Travelling through the desert, players can passively interact with other players they meet along the way, but cannot communicate via speech or text and cannot see each other's names until after the game's credits. The only form of communication between the two is a musical chime, which can be used to activate flying pieces of cloth or to befriend friendly creatures. The players can also assist each other, but cannot hinder each other, and are not able to differentiate between the two types of players.",
        developer: "Thatgamecompany",
        ratings: "4.8 / 5",
        players: "990k",
        mrp: 3599,
        year: 2012,
        gameSize: "4 GB",
        ss: ["https://imgur.com/rvUfaZj.jpg", "https://imgur.com/bkjhp3Y.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
  {
    title: "Platformer",
    items: [
      {
        id: 29,
        name: "Celeste",
        imageUrl: "https://imgur.com/kcHxBoH.jpg",
        price: 1299,
        description:
          "Celeste is a platforming video game by Canadian video game developers Matt Thorson and Noel Berry, with art by the Brazilian studio MiniBoss. The game was originally created as a prototype in four days during a game jam, and later expanded into a full release. Celeste was released in January 2018 on Microsoft DeviceObj.windows, Nintendo Switch, PlayStation 4, Xbox One, DeviceObj.macOS, and DeviceObj.linux. Alongside the game's release, Thorson announced that Extremely OK Games, consisting of Thorson and several others who worked on Celeste, would be formed to continue developing games. The game was released to critical acclaim, with many critics calling it one of the best games of 2018. It was nominated for several awards and won Best Independent Game and Games for Impact at The Game Awards 2018, and was nominated for four awards at the 14th British Academy Games Awards, including Best Game.",
        developer: "Matt Makes Games",
        ratings: "4.5 / 5",
        players: "5M",
        mrp: 4599,
        year: 2018,
        gameSize: "2 GB",
        ss: ["https://imgur.com/dRYqgDy.jpg", "https://imgur.com/pgrzfzf.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 30,
        name: "Katana Zero",
        imageUrl: "https://imgur.com/YJpqOPX.jpg",
        price: 999,
        description:
          "Katana Zero is a 2D action platform video game developed by Askiisoft and published by Devolver Digital. It was released for Microsoft DeviceObj.windows and Nintendo Switch on April 18, 2019, and for Xbox One on October 15, 2020. The game sold over 100,000 copies in its first week and was nominated for several awards, including Best Action Game at The Game Awards 2019.",
        developer: "Askiisoft",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2019,
        gameSize: "1 GB",
        ss: ["https://imgur.com/FovDYIO.jpg", "https://imgur.com/UDV5Wjf.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 31,
        name: "The Artful Escape",
        imageUrl: "https://imgur.com/4kK1JY9.jpg",
        price: 599,
        description:
          "The Artful Escape is an upcoming platform video game developed by Beethoven & Dinosaur and published by Annapurna Interactive. It is scheduled for release in 2021 for iOS, Microsoft DeviceObj.windows, and Xbox One.",
        developer: "Beethoven & Dinosaur",
        ratings: "4.5 / 5",
        players: "890k",
        mrp: 2599,
        year: 2021,
        gameSize: "3 GB",
        ss: ["https://imgur.com/qONxLq1.jpg", "https://imgur.com/fmSzys0.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 32,
        name: "Fez",
        imageUrl: "https://imgur.com/YcN8Kxk.jpg",
        price: 499,
        description:
          "Fez is a puzzle-platform game developed by Polytron Corporation and published by Trapdoor. The player-character Gomez receives a fez that reveals his two-dimensional (2D) world to be one of four sides of a three-dimensional (3D) world. The player rotates between these four 2D views to realign platforms and solve the game's puzzles. The object of the game is to collect cubes and cube fragments to restore order to the universe.",
        developer: "Polytron Corporation",
        ratings: "4.6 / 5",
        players: "990k",
        mrp: 1599,
        year: 2012,
        gameSize: "2 GB",
        ss: ["https://imgur.com/VA3rwYn.jpg", "https://imgur.com/ROa1eUu.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 33,
        name: "Shovel Knight",
        imageUrl: "https://imgur.com/6bMuplW.jpg",
        price: 1899,
        description:
          "Shovel Knight is a 2D side-scrolling platform game developed and published by Yacht Club Games. Following a successful Kickstarter crowdfunding campaign, the game was released for Microsoft DeviceObj.windows, Nintendo 3DS and Wii U in June 2014. Ports for DeviceObj.macOS and DeviceObj.linux followed in September of the same year. Ports for PlayStation 3, PlayStation 4, PlayStation Vita, Xbox One, and Amazon Fire TV were released in April 2015, and ports for Nintendo Switch and DeviceObj.windows Phone were released in 2017. Retail versions for PlayStation 4, PlayStation Vita, and Nintendo 3DS are distributed by U&I Entertainment. A spin-off titled Shovel Knight Dig is in development.",
        developer: "Yacht Club Games",
        ratings: "4.5 / 5",
        players: "2M",
        mrp: 3599,
        year: 2014,
        gameSize: "2 GB",
        ss: ["https://imgur.com/WTw6r1J.jpg", "https://imgur.com/XdHGW1A.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 34,
        name: "Spelunky 2",
        imageUrl: "https://imgur.com/bAXZaFm.jpg",
        price: 899,
        description:
          "Spelunky 2 is a 2020 platform video game developed by Mossmouth and BlitWorks. It is the sequel to Spelunky (2008) and was released for DeviceObj.windows and PlayStation 4 in September 2020, with a Nintendo Switch release announced for mid-2021. The game received universal acclaim from critics, who praised its gameplay and faithfulness to the original, but criticized its difficulty and multiplayer. It was nominated for several awards, including Best Action Game at The Game Awards 2020.",
        developer: "Mossmouth and BlitWorks",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2020,
        gameSize: "2 GB",
        ss: ["https://imgur.com/OC3pwqu.jpg", "https://imgur.com/5iQ6plC.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 35,
        name: "Monument Valley",
        imageUrl: "https://imgur.com/qHPvrDl.jpg",
        price: 1199,
        description:
          "Monument Valley is an indie puzzle game developed and published by Ustwo Games. The player leads the princess Ida through mazes of optical illusions and impossible objects while manipulating the world around her to reach various platforms. Monument Valley was developed over ten months beginning in early 2013 based on concept drawings by company artist Ken Wong. Its visual style was inspired by Japanese prints, minimalist sculpture, and indie games Windosill, Fez, and Sword & Sworcery, and was compared by critics to M. C. Escher drawings and Echochrome. The art was designed such that each frame would be worthy of public display.",
        developer: "Ustwo Games",
        ratings: "4.8 / 5",
        players: "10M",
        mrp: 2599,
        year: 2014,
        gameSize: "2 GB",
        ss: ["https://imgur.com/WDUSbO1.jpg", "https://imgur.com/TBqhTyx.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 36,
        name: "BattleBlock Theater",
        imageUrl: "https://imgur.com/cJc4weO.jpg",
        price: 599,
        description:
          "BattleBlock Theater is a comedy platform game developed by The Behemoth and published by Microsoft Studios for Xbox 360, DeviceObj.windows, DeviceObj.mac, and DeviceObj.linux. It is the third title from The Behemoth following Alien Hominid and Castle Crashers. The game was released on Xbox Live Arcade on April 3, 2013, and later temporarily made free via Games with Gold on July 16, 2014.",
        developer: "The Behemoth",
        ratings: "4.5 / 5",
        players: "500k",
        mrp: 2750,
        year: 2013,
        gameSize: "2 GB",
        ss: ["https://imgur.com/RKDqUrI.jpg", "https://imgur.com/GDk44JA.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
  {
    title: "RPGs",
    items: [
      {
        id: 37,
        name: "Disco Elysium",
        imageUrl: "https://imgur.com/121Fj7b.jpg",
        price: 2599,
        description:
          "Disco Elysium is a role-playing video game that features an open world and dialogue-heavy gameplay mechanics. The game is presented in an isometric perspective in which the player character is controlled. The player takes the role of a detective, who suffers from alcohol and drug-induced amnesia, on a murder case",
        developer: "Zaum Studio OÜ",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2019,
        gameSize: "10 GB",
        ss: ["https://imgur.com/LREYxyF.jpg", "https://imgur.com/T8vrNQv.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 38,
        name: "Chained Echoes",
        imageUrl: "https://imgur.com/21sYjPx.jpg",
        price: 2599,
        description:
          "Take up your sword, channel your magic or board your Mech. Chained Echoes is a 16-bit style RPG set in a fantasy world where dragons are as common as piloted mechanical suits.",
        developer: "Matthias Linda",
        ratings: "4.5 / 5",
        players: "200k",
        mrp: 3599,
        year: 2022,
        gameSize: "1 GB",
        ss: ["https://imgur.com/bJVokk4.jpg", "https://imgur.com/NUD8KYt.jpg"],
        devices: [DeviceObj.windows, DeviceObj.mac],
      },
      {
        id: 39,
        name: "Tunic",
        imageUrl: "https://imgur.com/i94opqN.jpg",
        price: 1599,
        description:
          "Explore a land filled with lost legends, ancient powers, and ferocious monsters in TUNIC, an isometric action game about a small fox on a big adventure. Stranded in a ruined land, and armed with only your own curiosity, you will confront colossal beasts, collect strange and powerful items, and unravel long-lost secrets.",
        developer: "Andrew Shouldice, TUNIC Team",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2022,
        gameSize: "2 GB",
        ss: ["https://imgur.com/GNZLWpG.jpg", "https://imgur.com/RjDnibV.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 40,
        name: "The Forgotten City",
        imageUrl: "https://imgur.com/B6m7AuS.jpg",
        price: 1599,
        description:
          "The Forgotten City is a mystery adventure role-playing game developed by Australian developer Modern Storyteller and published by Dear Villagers with additional support from Film Victoria. It is a full video game adaptation of the critically-acclaimed The Elder Scrolls V: Skyrim mod of the same name.",
        developer: "Modern Storyteller",
        ratings: "4.6 / 5",
        players: "990k",
        mrp: 2599,
        year: 2015,
        gameSize: "26 GB",
        ss: ["https://imgur.com/vEKMEVJ.jpg", "https://imgur.com/uRt6NUN.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 41,
        name: "Lisa: The Painful",
        imageUrl: "https://imgur.com/AScee9g.jpg",
        price: 2599,
        description:
          " Lisa: The Painful is a post-apocalyptic role-playing video game developed and published by American indie studio Dingaling Productions. The game was written, designed, and composed for by Austin Jorgensen, and was released for Microsoft DeviceObj.windows, DeviceObj.macOS, and DeviceObj.linux on 15 December 2014.",
        developer: "Dingaling Productions",
        ratings: "4.5 / 5",
        players: "5M",
        mrp: 3599,
        year: 2014,
        gameSize: "2 GB",
        ss: ["https://imgur.com/EERjguU.jpg", "https://imgur.com/11gBH7c.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 42,
        name: "Bastion",
        imageUrl: "https://imgur.com/1fM4Sp4.jpg",
        price: 1999,
        description:
          "Bastion is an action role-playing video game developed by independent developer Supergiant Games and originally published in 2011 by Warner Bros. Interactive Entertainment. In the game, the player controls 'the Kid' as he moves through floating, fantasy-themed environments and fights enemies of various types.",
        developer: "Supergiant Games",
        ratings: "4.8 / 5",
        players: "2M",
        mrp: 3599,
        year: 2011,
        gameSize: "2 GB",
        ss: ["https://imgur.com/ARQ6C7P.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 43,
        name: "Undertale",
        imageUrl: "https://imgur.com/Hm97fuL.jpg",
        price: 150,
        description:
          "Undertale is a role-playing video game created by indie developer Toby Fox. The player controls a child who has fallen into the Underground: a large, secluded region under the surface of the Earth, separated by a magic barrier. The player meets various monsters during a quest to return to the surface, mainly through the combat system; the player navigates through mini-bullet hell attacks by the opponent, and can opt to pacify or subdue monsters in order to spare them instead of murdering them.",
        developer: "Toby Fox",
        ratings: "4.9 / 5",
        players: "50M",
        mrp: 500,
        year: 2015,
        gameSize: "2 GB",
        ss: ["https://imgur.com/ZFB7tNv.jpg", "https://imgur.com/qHjKRtO.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 44,
        name: "Transistor",
        imageUrl: "https://imgur.com/1NBqSfE.jpg",
        price: 1999,
        description:
          "Transistor is a science fiction action role-playing video game developed and published by Supergiant Games. The game was released in May 2014 for Microsoft DeviceObj.windows and PlayStation 4, and for OS X and DeviceObj.linux in October 2014, and iOS devices in June 2015.",
        developer: "Supergiant Games",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2014,
        gameSize: "5 GB",
        ss: ["https://imgur.com/xNPfDYE.jpg", "https://imgur.com/d9OseHk.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 45,
        name: "The Binding of Isaac: Rebirth",
        imageUrl: "https://imgur.com/icenhJg.jpg",
        price: 1999,
        description:
          "The Binding of Isaac: Rebirth is an indie roguelike video game designed by Edmund McMillen and developed and published by Nicalis. Rebirth was released for Microsoft DeviceObj.windows, OS X, DeviceObj.linux, PlayStation 4, and PlayStation Vita in November 2014, and for Xbox One, New Nintendo 3DS, and Wii U in July 2015.",
        developer: "Edmund McMillen, Nicalis",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2014,
        gameSize: "2 GB",
        ss: ["https://imgur.com/fAQbZqH.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
  {
    title: "Puzzle",
    items: [
      {
        id: 46,
        name: "The Case of the Golden Idol",
        imageUrl: "https://imgur.com/RCRSTQk.jpg",
        price: 1200,
        description:
          "The Case of the Golden Idol is a puzzle game developed by American studio Little Grey Box and published by American studio Little Grey Box. It was released on 1 January 2021 for Microsoft DeviceObj.windows, DeviceObj.macOS, and DeviceObj.linux.",
        developer: "Little Grey Box",
        ratings: "4.5 / 5",
        players: "599k",
        mrp: 2599,
        year: 2021,
        gameSize: "2 GB",
        ss: ["https://imgur.com/G8ED4nx.jpg", "https://imgur.com/mI4BaBa.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 47,
        name: "Gorogoa",
        imageUrl: "https://imgur.com/0Cp2Nhu.jpg",
        price: 599,
        description:
          "Gorogoa is a puzzle video game developed by American studio Buried Signal and published by Annapurna Interactive. The game was released for Microsoft DeviceObj.windows, Nintendo Switch, iOS, and Android in December 2017, PlayStation 4 and Xbox One in May 2018, and for the Xbox Game Pass subscription service in October 2020.",
        developer: "Buried Signal",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2017,
        gameSize: "2 GB",
        ss: ["https://imgur.com/dhRMqIW.jpg", "https://imgur.com/vuJ1obV.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 48,
        name: "Vampire Survivors",
        imageUrl: "https://imgur.com/ZjTlpTf.jpg",
        price: 899,
        description:
          "Vampire Survivors is a puzzle game developed by American studio Little Grey Box and published by American studio Little Grey Box. It was released on 1 January 2021 for Microsoft DeviceObj.windows, DeviceObj.macOS, and DeviceObj.linux.",
        developer: "Little Grey Box",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 1599,
        year: 2021,
        gameSize: "2 GB",
        ss: ["https://imgur.com/6jmX2nf.jpg", "https://imgur.com/pTH3gft.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 49,
        name: "Ikaruga",
        imageUrl: "https://imgur.com/DXxLuy6.jpg",
        price: 1599,
        description:
          "Ikaruga is a shoot 'em up developed by Treasure. It is the spiritual sequel to Radiant Silvergun and was originally released in Japanese arcades in December 2001. The game's story follows a rebel pilot named Shinra as he battles an enemy nation using a specially designed fighter called the Ikaruga which can flip between two polarities, black and white.",
        developer: "Treasure",
        ratings: "4.7 / 5",
        players: "899k",
        mrp: 2599,
        year: 2001,
        gameSize: "1 GB",
        ss: ["https://imgur.com/VNSUbRG.jpg", "https://imgur.com/LSxO0HF.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 50,
        name: "Inside",
        imageUrl: "https://imgur.com/CCKuORA.jpg",
        price: 1399,
        description:
          "Inside is a puzzle-platformer adventure game developed and published by Playdead in 2016 for PlayStation 4, Xbox One and Microsoft DeviceObj.windows. The game was released for iOS in December 2017 and Nintendo Switch in June 2018. ",
        developer: "Playdead",
        ratings: "4.9 / 5",
        players: "10M",
        mrp: 3599,
        year: 2016,
        gameSize: "5 GB",
        ss: ["https://imgur.com/VnT8ta0.jpg", "https://imgur.com/84myZwK.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 51,
        name: "Her Story",
        imageUrl: "https://imgur.com/0jPrNsL.jpg",
        price: 599,
        description:
          "Her Story is an interactive movie video game written and directed by Sam Barlow. It was released on 24 June 2015 for Microsoft DeviceObj.windows, DeviceObj.mac OS X and iOS, and the Nintendo Switch on 14 August 2019. The game is based around a database search engine, which enables the player to search through a database of video clips of fictional police interviews, and to reveal portions of those clips that refer to the mystery of a murder.",
        developer: "Sam Barlow",
        ratings: "4.5 / 5",
        players: "1M",
        mrp: 2599,
        year: 2015,
        gameSize: "2 GB",
        ss: ["https://imgur.com/0knJ6Vb.jpg", "https://imgur.com/10dxPHc.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 52,
        name: "Gris",
        imageUrl: "https://imgur.com/YGblPln.jpg",
        price: 2599,
        description:
          "Gris is a hopeful young girl lost in her own world, dealing with a painful experience in her life. Her journey through sorrow is manifested in her dress, which grants new abilities to better navigate her faded reality.",
        developer: "Nomada Studio, Blitworks",
        ratings: "4.8 / 5",
        players: "1M",
        mrp: 3599,
        year: 2018,
        gameSize: "4 GB",
        ss: ["https://imgur.com/jqeIieM.jpg", "https://imgur.com/kA6pLSW.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 53,
        name: "Limbo",
        imageUrl: "https://imgur.com/W38wbvN.jpg",
        price: 699,
        description:
          "Dark, disturbing, yet eerily beautiful, Limbo is a world that deserves to be explored ~ Joystiq",
        developer: "Playdead",
        ratings: "4.9 / 5",
        players: "20M",
        mrp: 3599,
        year: 2010,
        gameSize: "2 GB",
        ss: ["https://imgur.com/vRtyhF3.jpg", "https://imgur.com/fqQIUFI.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 54,
        name: "OxenFree",
        imageUrl: "https://imgur.com/p15hDSf.jpg",
        price: 1299,
        description:
          "Oxenfree is a supernatural mystery graphic adventure game developed and published by Night School Studio. The game was released for Microsoft DeviceObj.windows, OS X and Xbox One in January 2016. PlayStation 4 and DeviceObj.linux versions were released later in 2016, followed by iOS, Android, and Nintendo Switch versions in 2017.",
        developer: "Night School Studio",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2016,
        gameSize: "2 GB",
        ss: ["https://imgur.com/lzMzSLY.jpg", "https://imgur.com/SjW5XvV.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 55,
        name: "Among Us",
        imageUrl: "https://imgur.com/yQmYxpR.jpg",
        price: 499,
        description:
          "Among Us is an online multiplayer social deduction game developed and published by American game studio InnerSloth and released on June 15, 2018. The game takes place in a space-themed setting, in which players each take on one of two roles, most being Crewmates, and a predetermined number being Impostors.",
        developer: "InnerSloth LLC",
        ratings: "4.8 / 5",
        players: "100M",
        mrp: 1599,
        year: 2018,
        gameSize: "1 GB",
        ss: ["https://imgur.com/emrUmTY.jpg", "https://imgur.com/MOtZEDW.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
  {
    title: "Simulation",
    items: [
      {
        id: 56,
        name: "Stardew Valley",
        imageUrl: "https://imgur.com/lYRIYmH.jpg",
        price: 599,
        description:
          "Stardew Valley is a simulation role-playing video game developed by Eric Barone. The game was initially released for Microsoft DeviceObj.windows in February 2016, with ports later being released for DeviceObj.macOS, DeviceObj.linux, PlayStation 4, Xbox One, Nintendo Switch, PlayStation Vita, iOS, and Android.",
        developer: "ConcernedApe",
        ratings: "4.5 / 5",
        players: "50M",
        mrp: 3599,
        year: 2016,
        gameSize: "2 GB",
        ss: ["https://imgur.com/MHYtQPv.jpg", "https://imgur.com/DTirtDg.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 57,
        name: "Spiritfarer",
        imageUrl: "https://imgur.com/XAu15gv.jpg",
        price: 1099,
        description:
          "Spiritfarer is a cozy management game about dying. You play Stella, ferrymaster to the deceased, a Spiritfarer. Build a boat to explore the world, then befriend and care for spirits before finally releasing them into the afterlife. Farm, mine, fish, harvest, cook, and craft your way across mystical seas.",
        developer: "Thunder Lotus Games",
        ratings: "4 / 5",
        players: "990k",
        mrp: 2599,
        year: 2020,
        gameSize: "2 GB",
        ss: ["https://imgur.com/Xts30D8.jpg", "https://imgur.com/HSuSYAX.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 58,
        name: "Papers, Please",
        imageUrl: "https://imgur.com/T6VbOL2.jpg",
        price: 499,
        description:
          "Papers, Please is a puzzle simulation video game created by indie game developer Lucas Pope, developed and published through his company, 3909 LLC. The game was released on August 8, 2013, for Microsoft DeviceObj.windows and OS X, for DeviceObj.linux on February 12, 2014, and for iOS on December 12, 2014.",
        developer: "3909 LLC",
        ratings: "4.9 / 5",
        players: "4M",
        mrp: 1599,
        year: 2013,
        gameSize: "1 GB",
        ss: ["https://imgur.com/aHd9uno.jpg", "https://imgur.com/7TmPOlH.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 59,
        name: "Gone Home",
        imageUrl: "https://imgur.com/sedOoWD.jpg",
        price: 799,
        description:
          "Gone Home is a first-person exploration video game developed and published by The Fullbright Company. Gone Home was first released for Microsoft DeviceObj.windows, OS X, and DeviceObj.linux computers in August 2013, followed by console releases for the PlayStation 4 and Xbox One in January 2016, the Nintendo Switch in September 2018, and iOS in December 2018.",
        developer: "The Fullbright Company",
        ratings: "4.5 / 5",
        players: "2M",
        mrp: 3599,
        year: 2013,
        gameSize: "2 GB",
        ss: ["https://imgur.com/OMNzD5y.jpg", "https://imgur.com/OlhBsqD.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 60,
        name: "Observation",
        imageUrl: "https://imgur.com/4vGiM3I.jpg",
        price: 1299,
        description:
          "Observation is a science fiction thriller video game developed by Scottish studio No Code and published by Devolver Digital. It was released for PlayStation 4 and Microsoft DeviceObj.windows in May 2019 and for Xbox One in June 2020. In Observation, the player assumes the role of SAM, an artificial intelligence aboard a space station, operating the station's control systems, cameras, and tools to assist Emma Fisher, a biologist, as she attempts to clarify the fate of the station's crew.",
        developer: "No Code",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2019,
        gameSize: "10 GB",
        ss: ["https://imgur.com/Tcezfhg.jpg", "https://imgur.com/Hp5bttg.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 61,
        name: "FTL: Faster Than Light",
        imageUrl: "https://imgur.com/yn0H6k0.jpg",
        price: 699,
        description:
          "FTL: Faster Than Light is a space-based top-down real-time strategy roguelike game created by indie developer Subset Games, which was released for Microsoft DeviceObj.windows, DeviceObj.macOS and DeviceObj.linux in September 2012. In the game, the player controls the crew of a single spacecraft, holding critical information to be delivered to an allied fleet, while being pursued by a large rebel fleet.",
        developer: "Subset Games",
        ratings: "4.5 / 5",
        players: "1M",
        mrp: 2599,
        year: 2012,
        gameSize: "2 GB",
        ss: ["https://imgur.com/wLqWaVN.jpg", "https://imgur.com/vVCviM0.jpg"],
        devices: [DeviceObj.windows],
      },
      {
        id: 62,
        name: "Untitled Goose Game",
        imageUrl: "https://imgur.com/u8PSqky.jpg",
        price: 399,
        description:
          "Untitled Goose Game is a 2019 puzzle stealth video game developed by House House and published by Panic. In the game, players control a goose who bothers the inhabitants of an English village. The player must use the goose's abilities to manipulate objects and non-player characters in order to complete specific objectives and progress through the game.",
        developer: "House House",
        ratings: "4.7 / 5",
        players: "10M",
        mrp: 3599,
        year: 2019,
        gameSize: "2 GB",
        ss: ["https://imgur.com/IRSpgV6.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
  {
    title: "Horror",
    items: [
      {
        id: 63,
        name: "Inscryption",
        imageUrl: "https://imgur.com/4NafW5q.jpg",
        price: 1599,
        description:
          "Inscryption is an in-development roguelike deck-building game with psychological horror elements. It is being developed by Daniel Mullins Games and published by Devolver Digital. The game is set to be released in 2021 for Microsoft DeviceObj.windows.",
        developer: "Daniel Mullins Games",
        ratings: "4.5 / 5",
        players: "990k",
        mrp: 3599,
        year: 2021,
        gameSize: "10 GB",
        ss: ["https://imgur.com/uF8GikM.jpg"],
        devices: [DeviceObj.windows, DeviceObj.mac],
      },
      {
        id: 64,
        name: "Outlast",
        imageUrl: "https://imgur.com/MeRynKa.jpg",
        price: 1099,
        description:
          "Outlast is a first-person survival horror video game developed and published by Red Barrels. The game revolves around a freelance investigative journalist, Miles Upshur, who decides to investigate a remote psychiatric hospital named Mount Massive Asylum, located deep in the mountains of Lake County, Colorado.",
        developer: "Red Barrels",
        ratings: "4.6 / 5",
        players: "50M",
        mrp: 3599,
        year: 2013,
        gameSize: "10 GB",
        ss: ["https://imgur.com/os9e5bE.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 65,
        name: "Little Nightmares II",
        imageUrl: "https://imgur.com/F1cUkzv.jpg",
        price: 599,
        description:
          "Little Nightmares is a puzzle-platform horror adventure game developed by Tarsier Studios and published by Bandai Namco Entertainment for PlayStation 4, DeviceObj.windows and Xbox One.",
        developer: "Tarsier Studios, Supermassive Games, Alike Studio",
        ratings: "4.5 / 5",
        players: "10M",
        mrp: 3599,
        year: 2021,
        gameSize: "10 GB",
        ss: ["https://imgur.com/blgd8SZ.jpg", "https://imgur.com/moMQesN.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
      {
        id: 66,
        name: "Soma",
        imageUrl: "https://imgur.com/QLIr3fZ.jpg",
        price: 2199,
        description:
          "Soma is a science fiction survival horror video game developed and published by Frictional Games for Microsoft DeviceObj.windows, OS X, DeviceObj.linux, PlayStation 4, and Xbox One. The game was released on 22 September 2015 for Microsoft DeviceObj.windows, OS X, DeviceObj.linux, PlayStation 4, and on 1 December 2017 on Xbox One.",
        developer: "Frictional Games",
        ratings: "4.5 / 5",
        players: "2M",
        mrp: 3599,
        year: 2015,
        gameSize: "10 GB",
        ss: ["https://imgur.com/HOhqhnJ.jpg"],
        devices: [DeviceObj.windows, DeviceObj.linux, DeviceObj.mac],
      },
    ],
  },
];

export default SHOP_DATA;
